# -*- coding: utf-8 -*-
"""Pattern Project (Phishing Website Detection)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0HyngTuwAAIEwyZGlcSVjHsEwi9sS4x
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load dataset with robust parameters
df = pd.read_csv('Webpages_Classification_test_data.csv',
                 sep=None,
                 engine='python',
                 on_bad_lines='skip',
                 encoding='latin1')

pd.set_option('display.max_columns', None)
display(df.head(20))

# Remove unnecessary columns
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)

# Drop raw strings and unique identifiers
df = df.drop(columns=['url', 'ip_add'], errors='ignore')

# Drop missing values and duplicates
df = df.dropna()
df = df.drop_duplicates()

print(f"Cleaned dataset shape: {df.shape}")

from sklearn.preprocessing import LabelEncoder

# Encode binary features
if 'https' in df.columns:
    df['https'] = df['https'].map({'yes': 1, 'no': 0})

# Encode target label
if 'label' in df.columns:
    df['label'] = df['label'].map({'good': 0, 'bad': 1})

# Encode categorical strings using LabelEncoder
le = LabelEncoder()
categorical_cols = ['geo_loc', 'tld', 'who_is', 'content']

for col in categorical_cols:
    if col in df.columns:
        df[col] = le.fit_transform(df[col].astype(str))

display(df.head())

# Technical info and statistics
print(df.info())
print("\nStatistical Summary:")
print(df.describe())

# Check target distribution
print("\nLabel Counts:")
print(df['label'].value_counts())

# Visualization
plt.figure(figsize=(8, 5))
sns.countplot(x='label', data=df)
plt.title('Target Label Distribution')
plt.show()

# Correlation Matrix and Heatmap
plt.figure(figsize=(12, 10))
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Feature Correlation Analysis')
plt.show()

from sklearn.preprocessing import StandardScaler

from imblearn.over_sampling import SMOTE
# Prepare features for PCA (exclude label)
X = df_final.drop('label', axis=1)
y = df_final['label']

# Spliting data into training and testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# applying SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Feature Selection (Dimension Reduction)
from sklearn.feature_selection import VarianceThreshold

  # 1. Remove Low Variance Features (Constant features)
selector = VarianceThreshold(threshold=0.01)
df_reduced = pd.DataFrame(selector.fit_transform(df), columns=df.columns[selector.get_support()])

  # 2. Remove Highly Correlated Features (Redundancy)
corr_matrix = df_reduced.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.85)]

  # Drop labels from features before selection if necessary
if 'label' in to_drop: to_drop.remove('label')
df_final = df_reduced.drop(columns=to_drop)

print(f"Features after selection: {df_final.columns.tolist()}")
print(f"Original shape: {df.shape}, Reduced shape: {df_final.shape}")

# Feature Extraction (PCA)
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from imblearn.over_sampling import SMOTE

# Scaling is mandatory for PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA to keep 95% of variance
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

print(f"Number of components after PCA: {pca.n_components_}")

"""> # Machine Learning Model"""

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import classification_report

print(y.value_counts(normalize=True))

# highly implanced dataset, this implance gets the ML model to always predict
# that the website is normal/legimated.


#balancing with SMOTE (wil do later)

#spletting the dataset to: test set and training set.

# Done befor the PCA and Feature selection

"""## Decision tree"""

# Training the model
dt = DecisionTreeClassifier(class_weight='balanced', random_state=42,max_depth=5)
dt.fit(X_train, y_train)

# Predictions
dt_y_pred = dt.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, dt_y_pred)
print("Accuracy:", accuracy)

"""

```
# This is formatted as code
```

## Random Forest
"""

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

#Training the model with the training inputs and outputs
rf = RandomForestClassifier(class_weight='balanced',max_depth=10)
rf.fit(X_train, y_train)

#Predictions
rf_y_pred = rf.predict(X_test)


#Evaluate predictions to real data
accuracy = accuracy_score(y_test, rf_y_pred)
print("Accuracy:", accuracy)

#will fix later
from sklearn.metrics import classification_report

print(classification_report(y_test, rf_y_pred))


from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf, X, y, cv=5)
print(scores)
print("Mean accuracy:", scores.mean())



"""## K-Nearest Neighbors (KNN)"""



"""## Logistic Regression"""



"""## Support Vector Machine (SVM)"""



"""## Extreme Gradient Boosting (XGBoost)"""

#all models for now to test


from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# If not installed:
# pip install xgboost
from xgboost import XGBClassifier

models = {
    "Random Forest": RandomForestClassifier(class_weight='balanced', max_depth=10),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(kernel='rbf', probability=True),
    "XGBoost": XGBClassifier(eval_metric='logloss')
}

results = {}

for name, model in models.items():
    print(f"\n===== {name} =====")

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    print("Test Accuracy:", acc)

    # Classification report
    print(classification_report(y_test, y_pred))

    # Cross-validation (IMPORTANT: use full dataset)
    scores = cross_val_score(model, X, y, cv=5)
    print("CV Scores:", scores)
    print("Mean CV Accuracy:", scores.mean())

    # Save result
    results[name] = scores.mean()